version: '3'
services:
  nginx:
    container_name: dontmd-nginx
    ports: 
      - 80:80
    build: nginx/.
    volumes:
      - ./nginx/:/etc/nginx/
    depends_on: 
      - dontmd-front
      - dontmd-api
      - dontmd-db
    networks:
      - dontmd_net_1

  dontmd-front:
    container_name: dontmd-frontend
    depends_on: 
      - dontmd-db
    ports: 
      - 8080:8080
    build: ./frontend
    volumes: 
      - ./frontend:/frontend
      - ./frontend/node_modules:/frontend/node_modules
    networks: 
      - dontmd_net_1

  dontmd-api:
    container_name: dontmd-api
    depends_on: 
      - dontmd-db
    ports: 
      - 3000:3000
    build: ./backend
    volumes: 
      - ./backend:/backend
      - ./backend/node_modules:/backend/node_modules
    networks: 
      - dontmd_net_1
  
  dontmd-db:
    container_name: dontmd-db
    image: mongo
    ports:
      - 27017:27017
    networks: 
      - dontmd_net_1

networks: 
  dontmd_net_1:
