version: '3'
services:
  # nginx:
  #   container_name: dontmd-nginx
  #   ports: 
  #     - 80:80
  #   build: nginx/.
  #   volumes:
  #     - ./nginx/:/nginx/
  #   depends_on: 
  #     - front-end
  #     - back-end
  #     - db
  #   networks:
  #     - net_1

  front-end:
    container_name: dontmd-frontend
    depends_on: 
      - db
    ports: 
      - 8080:8080
    build: ./frontend
    volumes: 
      - ./frontend:/frontend
      - ./frontend/node_modules:/frontend/node_modules
    networks: 
      - net_1

  api:
    container_name: dontmd-api
    depends_on: 
      - db
    ports: 
      - 3000:3000
    build: ./backend
    volumes: 
      - ./backend:/backend
      - ./backend/node_modules:/backend/node_modules
    networks: 
      - net_1
  
  db:
    container_name: dontmd-db
    image: mongo
    ports:
      - 27017:27017
    networks: 
      - net_1

networks: 
  net_1:
