version: '3'
services:
  nginx:
    container_name: dontmd-nginx
    ports: 
      - 80:80
    build: nginx/.
    volumes:
      - ./nginx/:/nginx/
    depends_on: 
      - front-end
      - back-end
      - db

  front-end:
    container_name: dontmd-frontend
    depends_on: 
      - db
    ports: 
      - 8080:8080
    build: ./frontend
    volumes: 
      - ./frontend:/frontend
      - ./frontend/node_modules:/frontend/node_modules

  back-end:
    container_name: dontmd-backend
    depends_on: 
      - db
    ports: 
      - 3000:3000
    build: ./backend
    volumes: 
      - ./backend:/backend
      - ./backend/node_modules:/backend/node_modules
  
  db:
    container_name: dontmd-db
    image: mongo
