version: '3'
services:
  dontmd-front:
    container_name: dontmd-frontend
    ports:
      - 8080:8080
    build: .
    volumes:
      - .:/frontend
      - ./node_modules:/frontend/node_modules
    # networks:
    #   - dontmd_net_1

# networks:
#   dontmd_net_1:
#     external: true
